version: '3.1'

services:
  mfptgbot:
    build:
      context: .
    environment:
      BOT_NAME: mfptgbot
      BOT_TOKEN: 6603544152:AAGSx1Qh3LFItBSaLBcBal8Yg_mlW8vZ-_w
    ports:
      - "8080:8080"
    restart: always
  mfp-db:
    image: mysql:5.7
    restart: always
    container_name: dev-mfp-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "dev-mfp-db"
      MYSQL_USER: root
      MYSQL_PASSWORD: root